version: "3"
volumes:
  uploads:
    external: false
  database:
    external: false
networks:
  services: {}
services:
  mysql-service:
    image: 10.10.11.6:8082/mysql:5
    restart: always
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp --disable-partition-engine-check
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybel
      MYSQL_USER: mybel
      MYSQL_PASSWORD: p@ssw0rd1234
      TZ: Asia/Jakarta
    ports:
      - 6603:3306
    volumes:
      - database:/var/lib/mysql
    networks:
      - services
  api-service:
    depends_on:
      - mysql-service
    image: "${MYBEL_IMAGE}"
    restart: always
    ports:
      - 4431:8484
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-services:3306/mybel?useSSL=false
      SPRING_DATASOURCE_USERNAME: mybel_user
      SPRING_DATASOURCE_PASSWORD: p@ssw0rd1234
    volumes:
      - uploads:/services/uploads
    networks:
      - services